"""aggregate_seeds.py — Markdown renders a snapshot of the overall shape.

test_aggregate_seeds.py 17 tests covering group/filter/column presence, but nothing nailed it
Complete markdown output** (header column width/table separator/section title/Method note segment).
Upgrading the tabulate library, changing the column order, or inserting chapters may cause the numbers referenced in the README to shift without anyone noticing.

This test uses 1 fixed DataFrame → render_markdown → complete string `==` snapshot."""

from __future__ import annotations

import pandas as pd

from aggregate_seeds import aggregate, render_markdown  # type: ignore[import-not-found]


def _row(task: str, model: str, agg: dict, created_at: str = "2026-05-10T00:00:00Z") -> dict:
    return {
        "run_id": f"r_{task}_{model}_{created_at}",
        "task": task,
        "model": model,
        "mode": "run",
        "created_at": created_at,
        "n": 50,
        "elapsed_ms": 1000.0,
        "num_fewshot": 0,
        "aggregated": agg,
    }


EXPECTED_MARKDOWN = """# Baseline aggregation (multi-seed mean ± std)

Generated by [`aggregate_seeds.py`](../aggregate_seeds.py) from `play/evals/runs/index.jsonl`.

## `bfcl_slice`

| metric     | `ollama:32b` (n=1)   | `ollama:7b` (n=2)   |
|------------|----------------------|---------------------|
| `accuracy` | 0.9000               | 0.5000 ± 0.1414     |

## Method note

样本标准差（pandas 默认 ddof=1）；单 seed run 显示 mean only；多 seed run 显示 mean ± std. 嵌套 metric（如 `accuracy_by_subject.philosophy`）由 `pd.json_normalize` 自动按 dot-path 展开.
"""


def test_render_markdown_snapshot():
    """deterministic 输入 → 字节级稳定 markdown 输出.
    """deterministic input → byte-level stable markdown output.

    Snapshot nailing: section title (`## ` double backtick task name) / column name `(n=K)` suffix / `±`
    Delimited / single seed only mean / Method note segment."""
    df = pd.DataFrame([
        _row("bfcl_slice", "ollama:7b@seed=0", {"accuracy": 0.4}),
        _row("bfcl_slice", "ollama:7b@seed=1", {"accuracy": 0.6}),
        _row("bfcl_slice", "ollama:32b@seed=0", {"accuracy": 0.9}),
    ])
    md = render_markdown(aggregate(df))
    assert md == EXPECTED_MARKDOWN, _diff_hint(md, EXPECTED_MARKDOWN)


def _diff_hint(got: str, expected: str) -> str:
    """Hit the first different line on hang - friendlier than 200 line diff."""
    g, e = got.splitlines(), expected.splitlines()
    for i, (gl, el) in enumerate(zip(g, e)):
        if gl != el:
            return f"line {i + 1} mismatch:\n  got:      {gl!r}\n  expected: {el!r}"
    if len(g) != len(e):
        return f"length mismatch: got={len(g)} expected={len(e)}"
    return "snapshot drift (no per-line diff found)"
