"""aggregate_seeds.py — markdown 渲染整体形状的 snapshot.

test_aggregate_seeds.py 17 个测试覆盖 group / filter / 列存在性，但**没有钉住
完整 markdown 输出**（表头列宽 / 表格分隔符 / 节标题 / Method note 段位）。
tabulate 库升级 / 改列顺序 / 章节插入都可能让 README 引用的数字位移而无人发觉.

本测把 1 个固定 DataFrame → render_markdown → 完整字符串 `==` snapshot.
"""

from __future__ import annotations

import pandas as pd

from aggregate_seeds import aggregate, render_markdown  # type: ignore[import-not-found]


def _row(task: str, model: str, agg: dict, created_at: str = "2026-05-10T00:00:00Z") -> dict:
    return {
        "run_id": f"r_{task}_{model}_{created_at}",
        "task": task,
        "model": model,
        "mode": "run",
        "created_at": created_at,
        "n": 50,
        "elapsed_ms": 1000.0,
        "num_fewshot": 0,
        "aggregated": agg,
    }


EXPECTED_MARKDOWN = """# Baseline aggregation (multi-seed mean ± std)

Generated by [`aggregate_seeds.py`](../aggregate_seeds.py) from `play/evals/runs/index.jsonl`.

## `bfcl_slice`

| metric     | `ollama:32b` (n=1)   | `ollama:7b` (n=2)   |
|------------|----------------------|---------------------|
| `accuracy` | 0.9000               | 0.5000 ± 0.1414     |

## Method note

样本标准差（pandas 默认 ddof=1）；单 seed run 显示 mean only；多 seed run 显示 mean ± std. 嵌套 metric（如 `accuracy_by_subject.philosophy`）由 `pd.json_normalize` 自动按 dot-path 展开.
"""


def test_render_markdown_snapshot():
    """deterministic 输入 → 字节级稳定 markdown 输出.

    Snapshot 钉死：节标题 (`## ` 双 backtick task 名) / 列名 `(n=K)` 后缀 / `±`
    分隔 / 单 seed 仅 mean / Method note 段位.
    """
    df = pd.DataFrame([
        _row("bfcl_slice", "ollama:7b@seed=0", {"accuracy": 0.4}),
        _row("bfcl_slice", "ollama:7b@seed=1", {"accuracy": 0.6}),
        _row("bfcl_slice", "ollama:32b@seed=0", {"accuracy": 0.9}),
    ])
    md = render_markdown(aggregate(df))
    assert md == EXPECTED_MARKDOWN, _diff_hint(md, EXPECTED_MARKDOWN)


def _diff_hint(got: str, expected: str) -> str:
    """挂时打第一个不同行——比 200 行 diff 友好."""
    g, e = got.splitlines(), expected.splitlines()
    for i, (gl, el) in enumerate(zip(g, e)):
        if gl != el:
            return f"line {i + 1} mismatch:\n  got:      {gl!r}\n  expected: {el!r}"
    if len(g) != len(e):
        return f"length mismatch: got={len(g)} expected={len(e)}"
    return "snapshot drift (no per-line diff found)"
